In [1]:
import numpy as np

In [3]:
import torch
from torch import Tensor

In [4]:
def multiples_of_ten(start: int, stop: int) -> Tensor:
    """
    Returns a Tensor of dtype torch.float64 that contains all of the multiples
    of ten (in order) between start and stop, inclusive. If there are no
    multiples of ten in this range then return an empty tensor of shape (0,).

    Args:
        start: Beginning ot range to create.
        stop: End of range to create (stop >= start).

    Returns:
        x: float64 Tensor giving multiples of ten between start and stop
    """
    assert start <= stop
    x = None
    ##########################################################################
    #                      TODO: Implement this function                     #
    ##########################################################################
    if ((start // 10 - stop // 10) == 0):
      return torch.tensor([], dtype = torch.float64)

    if (start % 10 == 0):
      x = torch.arange(start, (stop // 10 + 1) * 10, 10, dtype = torch.float64)
    else:
      x = torch.arange((start//10 + 1) * 10, (stop//10 + 1) * 10, 10, dtype = torch.float64)

    ##########################################################################
    #                            END OF YOUR CODE                            #
    ##########################################################################
    return x

In [7]:
print(multiples_of_ten(10, 40))
print(multiples_of_ten(9, 10))

tensor([10., 20., 30., 40.], dtype=torch.float64)
tensor([10.], dtype=torch.float64)


In [8]:
import torch

In [19]:
a = torch.tensor([
    [1, 2, 3, 4],
    [1, 2, 3, 4],
    [1, 2, 3, 4]
])

a.dim()

2

In [22]:
a[1] = 10

In [23]:
a

tensor([[ 1,  2,  3,  4],
        [10, 10, 10, 10],
        [ 1,  2,  3,  4]])

In [26]:
import numpy as np
a = np.array([0, 11, 22, 33, 44, 55, 66])
a[::-1]

array([66, 55, 44, 33, 22, 11,  0])

In [27]:
# Create a tensor, a slice, and a clone of a slice
a = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
b = a[0, 1:]
c = a[0, 1:].clone()
print('Before mutating:')
print(a)
print(b)
print(c)

a[0, 1] = 20  # a[0, 1] and b[0] point to the same element
b[1] = 30     # b[1] and a[0, 2] point to the same element
c[2] = 40     # c is a clone, so it has its own data
print('\nAfter mutating:')
print(a)
print(b)
print(c)

print(a.storage().data_ptr() == c.storage().data_ptr())

Before mutating:
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([2, 3, 4])
tensor([2, 3, 4])

After mutating:
tensor([[ 1, 20, 30,  4],
        [ 5,  6,  7,  8]])
tensor([20, 30,  4])
tensor([ 2,  3, 40])
False


In [29]:
a.storage().data_ptr()

140616876927232

In [33]:
a = torch.tensor([[1,2], [3, 4], [5, 6]])
y = a[ a > 3].clone()
sum(y).item()

15

In [52]:
x = torch.arange(24)
y = x.clone()
y.reshape(2, 3, 4).transpose(1, 2).reshape(-1)

tensor([[[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]],

        [[12, 16, 20],
         [13, 17, 21],
         [14, 18, 22],
         [15, 19, 23]]])

In [55]:
x = torch.arange(24)
x.reshape(1, -1).dim()

2

In [56]:
# Out-of-place addition creates and returns a new tensor without modifying the inputs:
x = torch.tensor([1, 2, 3])
y = torch.tensor([3, 4, 5])
print('Out-of-place addition:')
print('Before addition:')
print('x: ', x)
print('y: ', y)
z = x.add(y)  # Same as z = x + y or z = torch.add(x, y)
print('\nAfter addition (x and y unchanged):')
print('x: ', x)
print('y: ', y)
print('z: ', z)
print('z is x: ', z is x)
print('z is y: ', z is y)

Out-of-place addition:
Before addition:
x:  tensor([1, 2, 3])
y:  tensor([3, 4, 5])

After addition (x and y unchanged):
x:  tensor([1, 2, 3])
y:  tensor([3, 4, 5])
z:  tensor([4, 6, 8])
z is x:  False
z is y:  False


In [57]:

# In-place addition modifies the input tensor:
print('\n\nIn-place Addition:')
print('Before addition:')
print('x: ', x)
print('y: ', y)
x.add_(y)  # Same as x += y or torch.add(x, y, out=x)
print('\nAfter addition (x is modified):')
print('x: ', x)
print('y: ', y)
print('z: ', z)
print('z is x: ', z is x)
print('z is y: ', z is y)



In-place Addition:
Before addition:
x:  tensor([1, 2, 3])
y:  tensor([3, 4, 5])

After addition (x is modified):
x:  tensor([4, 6, 8])
y:  tensor([3, 4, 5])
z:  tensor([4, 6, 8])
z is x:  False
z is y:  False
