# Uniform Basic API

- **Estimator Interface** for building and fitting the models
- **Predictor Interface** for making predictions
- **Transformer Interface** for converting data

## Various Conventions

### Type Casting
- input should be cast to float64

In [7]:
from sklearn import random_projection
import numpy as np

rand_seed = np.random.RandomState(0)
X = rand_seed.rand(10, 2000)

transformer = random_projection.GaussianRandomProjection()
X_tran = transformer.fit_transform(X)
X_tran.dtype, X.dtype

(dtype('float64'), dtype('float64'))

### Refitting & Updating Paras

- Hyperparas can be updated and refitted after doing set_param()

In [9]:
from sklearn.datasets import load_iris
from sklearn.svm import SVC

X, y = load_iris(return_X_y = True)
model = SVC()
model.set_params(kernel = "linear").fit(X, y)

(10, 1973)

### Multiclass & Multilabel Fitting
- Use **LabelBinarizer().fit_transform(y)** to transfer multiclass labels to one-hot vectors.

In [13]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import LabelBinarizer
from sklearn.svm import SVC
X = [[1, 2],
     [3, 4],
     [4, 5],
     [5, 2],
     [1, 1]]
y = [0, 0, 1, 1, 2]

model = OneVsRestClassifier(SVC(gamma = "scale", random_state = 0))
model.fit(X, y).predict(X)

array([0, 1, 1, 1, 2])

In [15]:
X = [[1, 2],
     [3, 4],
     [4, 5],
     [5, 2],
     [1, 1]]
y = [0, 0, 1, 1, 2]
y = LabelBinarizer().fit_transform(y) # transfer to one-hot vector
print(y)

[[1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]]


array([[0, 0, 0],
       [0, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 0]])