In [1]:
import numpy as np
import scipy.linalg

In [2]:
A = [
    [1, 2, 3],
    [1, 1, 3],
    [1, 0, 3]
]
U, s, VT = np.linalg.svd(A)

In [3]:
U

array([[-0.63093591,  0.65973723,  0.40824829],
       [-0.57557828, -0.04519932, -0.81649658],
       [-0.52022065, -0.75013586,  0.40824829]])

In [4]:
s

array([5.76128066e+00, 1.34448696e+00, 2.22044605e-17])

In [5]:
VT

array([[-0.29971372, -0.31893084, -0.89914115],
       [-0.10085479,  0.94777799, -0.30256436],
       [ 0.9486833 ,  0.        , -0.31622777]])